
image_channels: 3
image_size: 256
num_channels: 128
channel_multipliers: [1, 1, 2, 2, 4, 4,]
attention_resolutions: [16]
num_steps: 1000
batch_size: 4
epochs: 100
grad_clip: 1.
dropout: 0.0
learning_rate: 2.e-5
warmup: 5000
ema_decay: 0.9999
flip: True
beta_start: 0.0001
beta_end: 0.02
model_var_type: fixed_small
use_ddim: True
dir_paths:
  - /celeba_hq/train/male
  - /celeba_hq/train/female
  - /celeba_hq/val/male
  - /celeba_hq/val/female 

